# Generated by Django 6.0.2 on 2026-02-13 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('processo', models.CharField(max_length=50)),
                ('pena_total_dias', models.IntegerField()),
                ('data_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRABALHO', 'Trabalho'), ('ESTUDO', 'Estudo'), ('LEITURA', 'Leitura')], max_length=10)),
                ('quantidade', models.IntegerField(help_text='Dias trabalhados, horas de estudo ou livros lidos')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('detento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='detentos.detento')),
            ],
        ),
    ]
